collection_area: {pos_x: 0.9, pos_y: 0.4, pos_z: 0.0, orient_w: 0.691,orient_x: 0.0,orient_y: 0.0,orient_z: -0.723}
build_area: {pos_x: 0.89, pos_y: -0.556, pos_z: 0.0, orient_w: 0.690,orient_x: 0.0,orient_y: 0.0,orient_z: -0.724}

